CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    nickname VARCHAR(30) NOT NULL,
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) CHARSET=utf8;

CREATE TABLE comment (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    comment VARCHAR(30) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE CASCADE
) CHARSET=utf8;