CREATE TABLE user (
    idx INT NOT NULL AUTO_INCREMENT,
    id VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(idx)
) CHARSET=utf8;

CREATE TABLE comment (
    idx INT NOT NULL AUTO_INCREMENT,
    user_idx INT NOT NULL,
    comment VARCHAR(30) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(idx),
    FOREIGN KEY (user_idx) REFERENCES user(idx) ON UPDATE CASCADE
) CHARSET=utf8;